config/routes.rb
Rails.application.routes.draw do
	mount Rswag::Ui::Engine => '/api-docs'
	mount Rswag::Api::Engine => '/api-docs'

	match '/oauth/authorize', to: 'oauth_applications#new',    via: 'get'
	match '/oauth/authorize', to: 'oauth_applications#create', via: 'post'

	use_doorkeeper
	devise_for :users

	# API Routes ==============
	namespace :api, defaults: { format: :json } do
		scope module: :v1,
			constraints: ApiConstraints.new(version: 1, default: true) do

				# Statistics
				match 'stats',                  to: 'stats#index',            via: 'get'

				# DEC112
				match '/dec112/register',       to: 'decs#register',          via: 'post'
				match '/dec112/query/:did',     to: 'decs#query',             via: 'get', constraints: {did: /[^\/]+/}
				match '/dec112/revoke',         to: 'decs#revoke',            via: 'delete'

				# SC Consent
				match '/consent',               to: 'consents#create',        via: 'post'
				match '/consent',               to: 'consents#index',         via: 'get'
				match '/consent/:id',           to: 'consents#show',          via: 'get'
				match '/consent/:id',           to: 'consents#update',        via: 'put'
				match '/consent/:id',           to: 'consents#delete',        via: 'delete'

				# QR Code handling
				match 'read_qr/:did',			to: 'qrs#read',               via: 'get', constraints: {did: /[^\/]+/}
				match 'connect',                to: 'qrs#qr_connect',         via: 'post'

				# App support
				match 'support/:nonce',         to: 'users#support',          via: 'get'
				match 'install/:key',           to: 'installs#show',          via: 'get'

				# User handling
				post 'users/create',            to: 'users#create'
				post 'users/confirm',           to: 'users#confirm'
				get  'users/show',              to: 'users#show'
				post 'users/do_remember',       to: 'users#do_remember'
				post 'users/remember',          to: 'users#remember'
				post 'users/forget',            to: 'users#forget'
				post 'users/update', 			to: 'users#update'
				post 'users/update_pwd',        to: 'users#update_pwd'
				post 'users/update_recv_pwd',   to: 'users#update_recv_pwd'
				get  'users/name_by_token/:id', to: 'users#name_by_token'
				get  'users/record_count',      to: 'users#record_count'
				get  'users/access_count',      to: 'users#access_count'
				match 'users/current',          to: 'users#current',          via: 'get'
				match 'users/archive',          to: 'users#archive',          via: 'get'
				match 'users/delete',           to: 'users#delete',           via: 'get'
				match 'users/app_support',      to: 'users#app_support',      via: 'post'
				match 'users/statistics',       to: 'users#statistics',       via: 'get'
				match 'users/hints',            to: 'users#hints',            via: 'get'
				match 'users/inactive_sources', to: 'users#inactive_sources', via: 'get'
				match 'users/reset_password',   to: 'users#reset_password',   via: 'post'
				match 'users/perform_password_reset', to: 'users#perform_password_reset', via: 'post'

				# App/Plugin handling
				get   'apps/index',             to: 'apps#index'
				post  'apps/destroy',           to: 'apps#destroy'
				match 'apps/:id',               to: 'apps#update', via: 'put'
				match 'apps/:id',               to: 'apps#show',   via: 'get'

				# true plugins (Doorkeeper::Application)
				match 'plugins/index',           to: 'plugins#index',           via: 'get'
				match 'plugins/create',          to: 'plugins#create',          via: 'post'
				match 'plugins/current',         to: 'plugins#current',         via: 'get'
				match 'plugins/:id',             to: 'plugins#show',            via: 'get'
				match 'plugins/:id',             to: 'plugins#update',          via: 'put'
				match 'plugins/:id',             to: 'plugins#delete',          via: 'delete'
				match 'plugins/identifier/:id',  to: 'plugins#show_identifier', via: 'get', constraints: {id: /[^\/]+/}
				# match 'plugins/:id/configure',   to: 'plugins#configure', via: 'post'
				match 'plugins/:id/manifest',    to: 'plugins#manifest_update', via: 'put'
				match  '/plugin/:id/assist',     to: 'plugins#assist',          via: 'get', constraints: {id: /[^\/]+/}
				match  '/plugin/:id/assist',     to: 'plugins#assist_update',   via: 'put', constraints: {id: /[^\/]+/}

				# Source handling
				match 'sources/index',           to: 'sources#index',     via: 'get'
				match 'sources/inactive',        to: 'sources#inactive',  via: 'get'
				match 'sources/:id',             to: 'sources#show',      via: 'get'
				match 'sources/:id',			 to: 'sources#update',    via: 'put'
				match 'sources/:id',             to: 'sources#delete',    via: 'delete'
				match 'sources/:id/configure',   to: 'sources#configure', via: 'post'
				match 'sources/:id/pile',        to: 'sources#new_pile',  via: 'post'
				match 'sources/:id/last_pile',   to: 'sources#last_pile', via: 'get'
				match 'piles/:id',               to: 'sources#show_pile', via: 'get'

				# View handling
				match 'views/:id',    to: 'views#update', via: 'put'
				match 'views/:id',    to: 'views#show',   via: 'get'
				# legacy for animal mobile oyd app
				match 'modules/index', to: 'views#mobile_index', via: 'get'
				
				# Permission handling
				match 'apps/:plugin_id/perms',         to: 'perms#index',      via: 'get'
				match 'apps/:plugin_id/perms',         to: 'perms#create',     via: 'post'
				match 'apps/:plugin_id/perms/:id',     to: 'perms#update',     via: 'put'
				match 'apps/:plugin_id/perms/:id',     to: 'perms#delete',     via: 'delete'
				match 'apps/:plugin_id/perms_destroy', to: 'perms#delete_all', via: 'post'

				# Permission handling
				match 'plugins/:plugin_id/perms',         to: 'perms#index',      via: 'get'
				match 'plugins/:plugin_id/perms',         to: 'perms#create',     via: 'post'
				match 'plugins/:plugin_id/perms/:id',     to: 'perms#update',     via: 'put'
				match 'plugins/:plugin_id/perms/:id',     to: 'perms#delete',     via: 'delete'
				match 'plugins/:plugin_id/perms_destroy', to: 'perms#delete_all', via: 'post'

				# Repo handling
				match 'repos/index',           to: 'repos#index',   via: 'get'
				match 'repos/:id',             to: 'repos#show',    via: 'get'
				match 'repos(/:identifier)/identifier', to: 'repos#show_identifier', via: 'get', constraints: {identifier: /[^\/]+/}
				match 'repos/:id',             to: 'repos#delete',  via: 'delete'
				match 'repos/:id/items',       to: 'repos#items',   via: 'get'
				match 'repos/:id/count',       to: 'repos#count',   via: 'get'
				match 'repos/:id/pub_key',     to: 'repos#pub_key', via: 'get', constraints: {id: /[^\/]+/}
				# Repos for apps
				match 'apps/:plugin_id/repos', to: 'repos#apps',    via: 'get'

				# Item handling
				match 'repos/id/:id/items',                   to: 'items#index_id',  via: 'get'
				match 'repos/id/:repo_id/items/:id',          to: 'items#delete_id', via: 'delete'
				match 'repos(/:repo_identifier)/items',       to: 'items#create',    via: 'post',   constraints: {repo_identifier: /[^\/]+/}
				match 'repos(/:repo_identifier)/items',       to: 'items#index',     via: 'get',    constraints: {repo_identifier: /[^\/]+/}
				match 'repos(/:repo_identifier)/items/:id',   to: 'items#update',    via: 'put',    constraints: {repo_identifier: /[^\/]+/}
				match 'repos(/:repo_identifier)/items/:id',   to: 'items#delete',    via: 'delete', constraints: {repo_identifier: /[^\/]+/}
				match 'items/:id/details',                    to: 'items#details',   via: 'get',    as: "item_id"
				match 'dri/:dri/details',                     to: 'items#dri',       via: 'get'
				match 'items/count', 						  to: 'items#count',     via: 'get'

				# Item handling /api/data
				match '/data',                                to: 'data#index',       via: 'get'
				match '/data/:id',                            to: 'data#index',       via: 'get'
				match '/data',                                to: 'data#write',       via: 'post'
				match '/data/:id',                            to: 'data#write',       via: 'put'
				match '/data/:id', 							  to: 'data#delete',      via: 'delete'
				match '/meta/schemas',                        to: 'semantics#schema', via: 'get'
				match '/meta/tables',                         to: 'semantics#table',  via: 'get'
				match '/meta/info',                           to: 'semantics#info',   via: 'get'
				match '/meta/usage',                          to: 'users#usage',      via: 'get'
				match '/active',                              to: 'semantics#active', via: 'get'				

				#watermarking
				match 'watermark/recipients', to: 'watermarks#recipients', via: 'get'
				match 'watermark/:id',        to: 'watermarks#show',       via: 'get'
				match 'watermark/:id',        to: 'watermarks#apply',      via: 'post'

				# Scheduler
				match 'tasks/index',  to: 'tasks#index',  via: 'get'
				match 'tasks/active', to: 'tasks#active', via: 'get'
				match 'tasks/create', to: 'tasks#create', via: 'post'
				match 'tasks/:id',    to: 'tasks#update', via: 'put',   constraints: {id: /[^\/]+/}
				match 'tasks/:id',    to: 'tasks#delete', via: 'delete'

				# Answers
				match 'answers/index', to: 'answers#index', via: 'get'
				match 'answers/:id',   to: 'answers#show',  via: 'get'

				# Reports
				match 'reports/index', to: 'reports#index',  via: 'get'
				match 'reports/:id',   to: 'reports#show',   via: 'get'
				match 'reports/:id',   to: 'reports#update', via: 'put'

				# Logs
				match 'logs/index',  to: 'logs#index',  via: 'get'
				match 'logs/create', to: 'logs#create', via: 'post'

				# Blockchain
				match 'items/merkle',   to: 'items#merkle',             via: 'get'
				match 'items/:id',      to: 'items#item_merkle_update', via: 'put'
				match 'merkles/create', to: 'items#merkle_create',      via: 'post'
				match 'merkles/:id',    to: 'items#merkle_update',      via: 'put'

				# News
				match 'news', to: 'news#current', via: 'get'

				# Sharing & Watermarking

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    include ApplicationHelper
    def home
        if logged_in?
            redirect_to user_path
        end
    end

    def info
    end

    def gmaps
    end

    def phone
    end

    def code
        @phone_number = params[:phone_number].to_s
        if request.post?
            redirect_to phone_code_path(phone_number: @phone_number)
            return
        end
        secret_code = (SecureRandom.random_number(9e5) + 1e5).to_i
        secret_code_text = secret_code.to_s + " " + oyd_backend_translate("secret_code", params[:locale])
        response_nil = false
        sms_url = "https://www.firmensms.at/gateway/senden.php"
        # sms_url = "https://www.firmensms.at/gateway/rest/"
        # auth_bearer = Base64.strict_encode64(ENV["SMS_USER"].to_s + ":"  + ENV["SMS_PWD"].to_s) rescue ""
        # hdr = { 'Accept' => '*/*',
        #         'Content-Type' => 'application/json',
        #         'Authorization' => 'Bearer ' + auth_bearer }
        # body = { 'route' => 3,
        #          'to' => @phone_number, 
        #          'text' => secret_code_text,
        #          'senderid' => "OwnYourData",
        #          'test' => 0,
        #          'deliveryreport' => 1 }
        body = "id=" + ENV["SMS_USER"].to_s
        body += "&pass=" + ENV["SMS_PWD"].to_s
        body += "&nummer=" + @phone_number.to_s
        body += "&absender=OwnYourData"
        body += "&route=3"
        body += "&text=" + secret_code_text.to_s
        begin
            response = HTTParty.post(sms_url, body: body )
        rescue => ex
            response_nil = true
        end
        if !response_nil && !response.body.nil? && response.code == 200
            @user = User.find_by_email(Base64.strict_encode64(Digest::SHA256.digest(@phone_number)).downcase)
            if !@user.nil?
                @user.update_attribute("sms_code", secret_code.to_s)
            end
        else
            flash[:warning] = oyd_backend_translate("sms_error", params[:locale])
            redirect_to login_path
            return
        end

    end

    def favicon
        send_file 'public/favicon.ico', type: 'image/x-icon', disposition: 'inline'
    end

    def test
    end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/code.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-1 col-md-push-7">
		<div class="panel panel-default" style="margin-top: 40px;">
		  	<div class="panel-heading">
		    	<h3 class="panel-title"><%= t('dialog.phone_login') %></h3>
		 	</div>
		  	<div class="panel-body">
		  		<% flash.each do |message_type, message| %>
					<div class="alert alert-<%= message_type %>"><%= message %></div>
				<% end %>
		  		<%= form_with url: login_path, id: "login_form" do |form| %>
		  			<%= form.hidden_field :password, value: @phone_number %>
		  			<%= form.hidden_field :email, value: Base64.strict_encode64(Digest::SHA256.digest(@phone_number)).downcase %>
		  			<%= form.hidden_field :cipher, id: "cipher" %>
		  			<%= form.hidden_field :nonce, id: "nonce" %>
		  			<span><%= t('dialog.code_info') %></span>
                    <fieldset>
			    	  	<div class="form-group">
			    	  		<%= form.text_field :phone_code, class: "form-control", placeholder: t('start.phone_code') %>
			    		</div>
						<%= form.button t('dialog.login'), id: "submit_form_button",
							class: "btn btn-success btn-lg btn-block",
							data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> " + t('dialog.submitBtn') } %>
						<%= link_to t('start.resendSMS'), phone_code_path(phone: @phone_number), class: "pull-right need-help", style: "margin-top: 15px;" %><span class="clearfix"></span>
			    	</fieldset>
		      	<% end %>
		    </div>
		</div>
		<div style="margin: -10px auto 60px; display: table;">
			<%= link_to t('dialog.emailLogin'), login_path %>
		</div>
	</div>
	<div class="col-md-7 col-md-pull-5">
		<h3 style="font-weight: 700; color: #666666;"><%= t('start.header') %></h3>
		<h3 style="line-height: 1.7em; color: #666666;"><%= t('start.text') %></h3>
		<%= image_tag("oyd-picture_" + I18n.locale.to_s + ".png",  class: "img-responsive", alt: "OwnYourData", style: "padding:4%;") %>
	</div>
</div>
<script>
    window.sodium = { onload: function (sodium) { } };
	$('#submit_form_button').click(function(e){
		e.preventDefault();
		myKey = sodium.crypto_box_keypair();
		nonce = sodium.randombytes_buf(24);
		authentication_key = sodium.crypto_hash_sha256(sodium.from_string("auth"));
		message_raw = sodium.from_string("<%= @phone_number %>");
		cipher = sodium.crypto_box_easy(message_raw, nonce, myKey.publicKey, authentication_key);
		$('#cipher').val(sodium.to_hex(cipher));
		$('#nonce').val(sodium.to_hex(nonce));
		localStorage.setItem('app_support', sodium.to_hex(myKey.privateKey));
		// sessionStorage['app_support'] = sodium.to_hex(myKey.privateKey);
		$('#login_form').submit();
	})

</script>
<script src="/sodium.js" async></script>

app/views/static_pages/gmaps.html.erb
<% provide(:title, 'Info') %>

<p>&nbsp;</p>
<div class="container">
    <div class="row">
    	<div class="col-md-4 col-md-offset-4">
    		<div class="panel panel-default">
			  	<div class="panel-heading">
			    	<h3 class="panel-title">Maps Chatbot</h3>
			 	</div>
			  	<div class="panel-body">
                    <fieldset>
			    	  	<div class="form-group">
			    	  		<p>Scan QR-code to connect to OwnYourData Data Vault</p>
			    	  		<p style="text-align: center;"><%= image_tag 'gmaps_qr.png', style: "height: 176px;" %></p>
			    	  		<%= link_to t('general.startpage'), root_path %>
			    		</div>
			    	</fieldset>
			    </div>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-1 col-md-push-7">
		<div class="panel panel-default" style="margin-top: 40px;">
		  	<div class="panel-heading">
		    	<h3 class="panel-title"><%= t('dialog.login') %></h3>
		 	</div>
		  	<div class="panel-body">
		  		<% flash.each do |message_type, message| %>
					<div class="alert alert-<%= message_type %>"><%= message %></div>
				<% end %>
		  		<%= form_with url: login_path, id: "login_form" do |form| %>
		  			<%= form.hidden_field :cipher, id: "cipher" %>
		  			<%= form.hidden_field :nonce, id: "nonce" %>
                    <fieldset>
			    	  	<div class="form-group">
			    	  		<%= form.email_field :email, class: "form-control", placeholder: t('start.email') %>
			    		</div>
			    	  	<div class="form-group">
			    	  		<%= form.password_field :password, id: "login_password", class: "form-control", placeholder: t('start.password') %>
			    		</div>
						<%= form.button t('dialog.submitBtn'), id: "submit_form_button",
							class: "btn btn-success btn-lg btn-block",
							data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> " + t('dialog.submitBtn') } %>
						<div class="form-group" style="margin-left: 20px;">
							<div class="checkbox pull-left" style="margin-bottom: 0;">
								<%= form.check_box :remember, style: "width: inherit;" %>
								<%= t('start.remember') %>
							</div>
						</div>
						<%= link_to t('start.forgot'), password_reset_path, class: "pull-right need-help", style: "margin-top: -5px;" %>
						<span class="clearfix"></span>
			    	</fieldset>
		      	<% end %>
		    </div>
		</div>
		<div style="margin: -10px auto 60px; display: table; text-align: center;">
			<%= link_to t('dialog.signUp'), new_path %><br>
			<%= link_to t('start.login_SOWL'), login_sowl_path %>
		</div>
	</div>
	<div class="col-md-7 col-md-pull-5">
		<h3 style="font-weight: 700; color: #666666;"><%= t('start.header') %></h3>
		<h3 style="line-height: 1.7em; color: #666666;"><%= t('start.text') %></h3>
		<%= image_tag("oyd-picture_" + I18n.locale.to_s + ".png",  class: "img-responsive", alt: "OwnYourData", style: "padding:4%;") %>
	</div>
</div>
<script>
    window.sodium = { onload: function (sodium) { } };
	$('#submit_form_button').click(function(e){
		e.preventDefault();
		myKey = sodium.crypto_box_keypair();
		nonce = sodium.randombytes_buf(24);
		authentication_key = sodium.crypto_hash_sha256(sodium.from_string("auth"));
		message_raw = sodium.from_string($('#login_password').val());
		cipher = sodium.crypto_box_easy(message_raw, nonce, myKey.publicKey, authentication_key);
		$('#cipher').val(sodium.to_hex(cipher));
		$('#nonce').val(sodium.to_hex(nonce));
		localStorage.setItem('app_support', sodium.to_hex(myKey.privateKey));
		// sessionStorage['app_support'] = sodium.to_hex(myKey.privateKey);
		$('#login_form').submit();
	})

</script>
<script src="/sodium.js" async></script>

app/views/static_pages/info.html.erb
<% provide(:title, 'Info') %>

<p>&nbsp;</p>
<div class="container">
    <div class="row">
    	<div class="col-md-4 col-md-offset-4">
    		<div class="panel panel-default">
			  	<div class="panel-heading">
			    	<h3 class="panel-title"><%= params[:title] %></h3>
			 	</div>
			  	<div class="panel-body">
                    <fieldset>
			    	  	<div class="form-group">
			    	  		<p><%= params[:text] %></p>
			    	  		<%= link_to t('general.startpage'), root_path %>
			    		</div>
			    	</fieldset>
			    </div>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/phone.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-1 col-md-push-7">
		<div class="panel panel-default" style="margin-top: 40px;">
		  	<div class="panel-heading">
		    	<h3 class="panel-title"><%= t('dialog.phone_login') %></h3>
		 	</div>
		  	<div class="panel-body">
		  		<% flash.each do |message_type, message| %>
					<div class="alert alert-<%= message_type %>"><%= message %></div>
				<% end %>
		  		<%= form_with url: phone_code_path do |form| %>
                    <fieldset>
			    	  	<div class="form-group">
			    	  		<%= form.phone_field :phone_number, class: "form-control", placeholder: t('start.phone_number') %>
			    		</div>
						<%= form.button t('dialog.requestCodeBtn'), id: "submit_form_button",
							class: "btn btn-success btn-lg btn-block",
							data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> " + t('dialog.submitBtn') } %>
			    	</fieldset>
		      	<% end %>
		    </div>
		</div>
		<div style="margin: -10px auto 60px; display: table;">
			<%= link_to t('dialog.emailLogin'), login_path %>
		</div>
	</div>
	<div class="col-md-7 col-md-pull-5">
		<h3 style="font-weight: 700; color: #666666;"><%= t('start.header') %></h3>
		<h3 style="line-height: 1.7em; color: #666666;"><%= t('start.text') %></h3>
		<%= image_tag("oyd-picture_" + I18n.locale.to_s + ".png",  class: "img-responsive", alt: "OwnYourData", style: "padding:4%;") %>
	</div>
</div>