config/routes.rb
Rails.application.routes.draw do
	mount Rswag::Ui::Engine => '/api-docs'
	mount Rswag::Api::Engine => '/api-docs'

	match '/oauth/authorize', to: 'oauth_applications#new',    via: 'get'
	match '/oauth/authorize', to: 'oauth_applications#create', via: 'post'

	use_doorkeeper
	devise_for :users

	# API Routes ==============
	namespace :api, defaults: { format: :json } do
		scope module: :v1,
			constraints: ApiConstraints.new(version: 1, default: true) do

				# Statistics
				match 'stats',                  to: 'stats#index',            via: 'get'

				# DEC112
				match '/dec112/register',       to: 'decs#register',          via: 'post'
				match '/dec112/query/:did',     to: 'decs#query',             via: 'get', constraints: {did: /[^\/]+/}
				match '/dec112/revoke',         to: 'decs#revoke',            via: 'delete'

				# SC Consent
				match '/consent',               to: 'consents#create',        via: 'post'
				match '/consent',               to: 'consents#index',         via: 'get'
				match '/consent/:id',           to: 'consents#show',          via: 'get'
				match '/consent/:id',           to: 'consents#update',        via: 'put'
				match '/consent/:id',           to: 'consents#delete',        via: 'delete'

				# QR Code handling
				match 'read_qr/:did',			to: 'qrs#read',               via: 'get', constraints: {did: /[^\/]+/}
				match 'connect',                to: 'qrs#qr_connect',         via: 'post'

				# App support
				match 'support/:nonce',         to: 'users#support',          via: 'get'
				match 'install/:key',           to: 'installs#show',          via: 'get'

				# User handling
				post 'users/create',            to: 'users#create'
				post 'users/confirm',           to: 'users#confirm'
				get  'users/show',              to: 'users#show'
				post 'users/do_remember',       to: 'users#do_remember'
				post 'users/remember',          to: 'users#remember'
				post 'users/forget',            to: 'users#forget'
				post 'users/update', 			to: 'users#update'
				post 'users/update_pwd',        to: 'users#update_pwd'
				post 'users/update_recv_pwd',   to: 'users#update_recv_pwd'
				get  'users/name_by_token/:id', to: 'users#name_by_token'
				get  'users/record_count',      to: 'users#record_count'
				get  'users/access_count',      to: 'users#access_count'
				match 'users/current',          to: 'users#current',          via: 'get'
				match 'users/archive',          to: 'users#archive',          via: 'get'
				match 'users/delete',           to: 'users#delete',           via: 'get'
				match 'users/app_support',      to: 'users#app_support',      via: 'post'
				match 'users/statistics',       to: 'users#statistics',       via: 'get'
				match 'users/hints',            to: 'users#hints',            via: 'get'
				match 'users/inactive_sources', to: 'users#inactive_sources', via: 'get'
				match 'users/reset_password',   to: 'users#reset_password',   via: 'post'
				match 'users/perform_password_reset', to: 'users#perform_password_reset', via: 'post'

				# App/Plugin handling
				get   'apps/index',             to: 'apps#index'
				post  'apps/destroy',           to: 'apps#destroy'
				match 'apps/:id',               to: 'apps#update', via: 'put'
				match 'apps/:id',               to: 'apps#show',   via: 'get'

				# true plugins (Doorkeeper::Application)
				match 'plugins/index',           to: 'plugins#index',           via: 'get'
				match 'plugins/create',          to: 'plugins#create',          via: 'post'
				match 'plugins/current',         to: 'plugins#current',         via: 'get'
				match 'plugins/:id',             to: 'plugins#show',            via: 'get'
				match 'plugins/:id',             to: 'plugins#update',          via: 'put'
				match 'plugins/:id',             to: 'plugins#delete',          via: 'delete'
				match 'plugins/identifier/:id',  to: 'plugins#show_identifier', via: 'get', constraints: {id: /[^\/]+/}
				# match 'plugins/:id/configure',   to: 'plugins#configure', via: 'post'
				match 'plugins/:id/manifest',    to: 'plugins#manifest_update', via: 'put'
				match  '/plugin/:id/assist',     to: 'plugins#assist',          via: 'get', constraints: {id: /[^\/]+/}
				match  '/plugin/:id/assist',     to: 'plugins#assist_update',   via: 'put', constraints: {id: /[^\/]+/}

				# Source handling
				match 'sources/index',           to: 'sources#index',     via: 'get'
				match 'sources/inactive',        to: 'sources#inactive',  via: 'get'
				match 'sources/:id',             to: 'sources#show',      via: 'get'
				match 'sources/:id',			 to: 'sources#update',    via: 'put'
				match 'sources/:id',             to: 'sources#delete',    via: 'delete'
				match 'sources/:id/configure',   to: 'sources#configure', via: 'post'
				match 'sources/:id/pile',        to: 'sources#new_pile',  via: 'post'
				match 'sources/:id/last_pile',   to: 'sources#last_pile', via: 'get'
				match 'piles/:id',               to: 'sources#show_pile', via: 'get'

				# View handling
				match 'views/:id',    to: 'views#update', via: 'put'
				match 'views/:id',    to: 'views#show',   via: 'get'
				# legacy for animal mobile oyd app
				match 'modules/index', to: 'views#mobile_index', via: 'get'
				
				# Permission handling
				match 'apps/:plugin_id/perms',         to: 'perms#index',      via: 'get'
				match 'apps/:plugin_id/perms',         to: 'perms#create',     via: 'post'
				match 'apps/:plugin_id/perms/:id',     to: 'perms#update',     via: 'put'
				match 'apps/:plugin_id/perms/:id',     to: 'perms#delete',     via: 'delete'
				match 'apps/:plugin_id/perms_destroy', to: 'perms#delete_all', via: 'post'

				# Permission handling
				match 'plugins/:plugin_id/perms',         to: 'perms#index',      via: 'get'
				match 'plugins/:plugin_id/perms',         to: 'perms#create',     via: 'post'
				match 'plugins/:plugin_id/perms/:id',     to: 'perms#update',     via: 'put'
				match 'plugins/:plugin_id/perms/:id',     to: 'perms#delete',     via: 'delete'
				match 'plugins/:plugin_id/perms_destroy', to: 'perms#delete_all', via: 'post'

				# Repo handling
				match 'repos/index',           to: 'repos#index',   via: 'get'
				match 'repos/:id',             to: 'repos#show',    via: 'get'
				match 'repos(/:identifier)/identifier', to: 'repos#show_identifier', via: 'get', constraints: {identifier: /[^\/]+/}
				match 'repos/:id',             to: 'repos#delete',  via: 'delete'
				match 'repos/:id/items',       to: 'repos#items',   via: 'get'
				match 'repos/:id/count',       to: 'repos#count',   via: 'get'
				match 'repos/:id/pub_key',     to: 'repos#pub_key', via: 'get', constraints: {id: /[^\/]+/}
				# Repos for apps
				match 'apps/:plugin_id/repos', to: 'repos#apps',    via: 'get'

				# Item handling
				match 'repos/id/:id/items',                   to: 'items#index_id',  via: 'get'
				match 'repos/id/:repo_id/items/:id',          to: 'items#delete_id', via: 'delete'
				match 'repos(/:repo_identifier)/items',       to: 'items#create',    via: 'post',   constraints: {repo_identifier: /[^\/]+/}
				match 'repos(/:repo_identifier)/items',       to: 'items#index',     via: 'get',    constraints: {repo_identifier: /[^\/]+/}
				match 'repos(/:repo_identifier)/items/:id',   to: 'items#update',    via: 'put',    constraints: {repo_identifier: /[^\/]+/}
				match 'repos(/:repo_identifier)/items/:id',   to: 'items#delete',    via: 'delete', constraints: {repo_identifier: /[^\/]+/}
				match 'items/:id/details',                    to: 'items#details',   via: 'get',    as: "item_id"
				match 'dri/:dri/details',                     to: 'items#dri',       via: 'get'
				match 'items/count', 						  to: 'items#count',     via: 'get'

				# Item handling /api/data
				match '/data',                                to: 'data#index',       via: 'get'
				match '/data/:id',                            to: 'data#index',       via: 'get'
				match '/data',                                to: 'data#write',       via: 'post'
				match '/data/:id',                            to: 'data#write',       via: 'put'
				match '/data/:id', 							  to: 'data#delete',      via: 'delete'
				match '/meta/schemas',                        to: 'semantics#schema', via: 'get'
				match '/meta/tables',                         to: 'semantics#table',  via: 'get'
				match '/meta/info',                           to: 'semantics#info',   via: 'get'
				match '/meta/usage',                          to: 'users#usage',      via: 'get'
				match '/active',                              to: 'semantics#active', via: 'get'				

				#watermarking
				match 'watermark/recipients', to: 'watermarks#recipients', via: 'get'
				match 'watermark/:id',        to: 'watermarks#show',       via: 'get'
				match 'watermark/:id',        to: 'watermarks#apply',      via: 'post'

				# Scheduler
				match 'tasks/index',  to: 'tasks#index',  via: 'get'
				match 'tasks/active', to: 'tasks#active', via: 'get'
				match 'tasks/create', to: 'tasks#create', via: 'post'
				match 'tasks/:id',    to: 'tasks#update', via: 'put',   constraints: {id: /[^\/]+/}
				match 'tasks/:id',    to: 'tasks#delete', via: 'delete'

				# Answers
				match 'answers/index', to: 'answers#index', via: 'get'
				match 'answers/:id',   to: 'answers#show',  via: 'get'

				# Reports
				match 'reports/index', to: 'reports#index',  via: 'get'
				match 'reports/:id',   to: 'reports#show',   via: 'get'
				match 'reports/:id',   to: 'reports#update', via: 'put'

				# Logs
				match 'logs/index',  to: 'logs#index',  via: 'get'
				match 'logs/create', to: 'logs#create', via: 'post'

				# Blockchain
				match 'items/merkle',   to: 'items#merkle',             via: 'get'
				match 'items/:id',      to: 'items#item_merkle_update', via: 'put'
				match 'merkles/create', to: 'items#merkle_create',      via: 'post'
				match 'merkles/:id',    to: 'items#merkle_update',      via: 'put'

				# News
				match 'news', to: 'news#current', via: 'get'

				# Sharing & Watermarking

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                       :bigint(8)        not null, primary key
#  email                    :string           default(""), not null
#  encrypted_password       :string           default(""), not null
#  reset_password_token     :string
#  reset_password_sent_at   :datetime
#  remember_created_at      :datetime
#  sign_in_count            :integer          default(0), not null
#  current_sign_in_at       :datetime
#  last_sign_in_at          :datetime
#  current_sign_in_ip       :inet
#  last_sign_in_ip          :inet
#  confirmation_token       :string
#  confirmed_at             :datetime
#  confirmation_sent_at     :datetime
#  unconfirmed_email        :string
#  full_name                :string
#  language                 :string
#  frontend_url             :string
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  recovery_password_digest :string
#  password_key             :string
#  recovery_password_key    :string
#  email_notif              :boolean
#  assist_relax             :boolean
#  last_item_count          :integer
#  remember_digest          :string
#  reset_digest             :string
#  reset_sent_at            :datetime
#  app_nonce                :string
#  app_cipher               :string
#  phone_hash               :string
#  phone_key                :string
#  did                      :string
#  sms_code                 :string
#  did_private_key          :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
	has_many :oauth_applications, class_name: 'Doorkeeper::Application', as: :owner, dependent: :destroy
	has_many :repos, dependent: :destroy
	has_many :backups, dependent: :destroy
	has_many :logs, dependent: :destroy
	has_many :plugin_assists, dependent: :destroy

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
			:recoverable, :rememberable, :trackable, :validatable, :confirmable

	attr_accessor :recovery_password, :recovery_password_confirmation, :remember_token

	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness:  { case_sensitive: false }

	def password_required?
		super if confirmed?
	end

	def password_match?
		self.errors[:password] << "can't be blank" if password.blank?
		self.errors[:recovery_password] << "can't be blank" if recovery_password.blank?
		self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
		self.errors[:recovery_password_confirmation] << "can't be blank" if recovery_password_confirmation.blank?
		self.errors[:recovery_password] << "shall not match password" if password == recovery_password
		self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
		self.errors[:recovery_password_confirmation] << "does not match recovery password" if recovery_password != recovery_password_confirmation
		password == password_confirmation && !password.blank? && recovery_password == recovery_password_confirmation && !recovery_password.blank? && password != recovery_password
	end

	def password_only_match?
		self.errors[:password] << "can't be blank" if password.blank?
		self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
		self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
		password == password_confirmation && !password.blank?
	end

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
													  BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def authenticated?(remember_token)
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end
end

app/views/users/_app_store.html.erb
<% if !@installed_apps_identifier.include? app_store["identifier"] %>
	<div class="col-lg-5ths col-md-3 col-sm-4 col-xs-6 col-wrapper"> 
		<div class="app-wrapper store-wrapper"> 
			<div class="plugin-picture-wrapper">
				<img src="<%= app_store["picture"] %>">
			</div> 
			<div class="app-item font-size-medium">
				<strong><%= app_store["name"] %></strong>
			</div> 
			<div class="app-item appInfo"> 
				<span>
					<%= app_store["description"].gsub("&uuml;","ü").gsub("&auml;","ä").gsub("&ouml;","ö") %>
				</span>
				<a href="<%= app_store["infourl"] %>" class="fakelink" style="padding: 0; margin: 0;">
					<%= t('apps.details') %>
				</a>
			</div>
			<div class="app-item">
				<%= link_to t('apps.install'), app_new_path(plugin_id: app_store["id"]), class: "custom-btn", method: :post %>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_count_list.html.erb
<li>
	<%= link_to count_list["count"].to_s, show_data_path(id: count_list["id"]) %>
</li>

app/views/users/_plugin_list.html.erb
<tr>
	<td class="col-lg-8 col-md-8 col-xs-10 font-size-large">
		<%= plugin_list["name"].to_s %><br>
		<span style="color: gray; font-size: small;"><%= plugin_list["description"].to_s %></span>
		<% if plugin_list["installation_hint"].to_s != "" %>
			<br><span style="color: darkgray; font-size: small;"><em><strong><%= t('plugins.installation_hint') %>:</strong> <%= plugin_list["installation_hint"].to_s.html_safe %>
			<% if plugin_list["access_code"].to_s == "" %>
				</em></span><%= link_to t('plugins.request_connection_key'), request_key_path(id: plugin_list["id"]), class: "btn btn-default btn-xs", style: "margin-top: -3px; margin-left: 8px;" %>
			<% else %>
				</em><%= plugin_list["access_code"].to_s %></span><%= link_to t('plugins.refresh_key'), request_key_path(id: plugin_list["id"]), class: "btn btn-default btn-xs", style: "margin-top: -3px; margin-left: 8px;" %>
			<% end %>
		<% end %>
 	</td>

	<td class="text-right col-lg-4 col-md-4 col-xs-2">
		<div class="btn-group flex-btn-group-container">
			<%= link_to(show_plugin_details_path(plugin_id: plugin_list["id"]), 
					class: "btn btn-primary btn-sm", remote: true) do  %>
				<span class="glyphicon glyphicon-pencil"></span>
				<span class="hidden-xs hidden-sm"><%= t('data.edit_label') %></span>
			<% end %>
			<% if plugin_list["update"].to_s.downcase == "true" %>
				<%= link_to(update_plugin_path(id: plugin_list["id"]), 
						class: "btn btn-success btn-sm") do  %>
					<span class="glyphicon glyphicon-exclamation-sign"></span>
					<span class="hidden-xs hidden-sm"><%= t('data.update_label') %></span>
				<% end %>
			<% end %>
			<%= link_to(plugin_remove_path(plugin_id: plugin_list["id"]), 
					class: "btn btn-danger btn-sm", method: :delete,
					data: { confirm: t('data.delete_question') }) do %>
				<span class="glyphicon glyphicon-remove-circle"></span>
				<span class="hidden-xs hidden-sm"><%= t('data.delete_label') %></span>
			<% end %>
		</div>
	</td>
</tr>

app/views/users/_repo_list.html.erb
<tr>
	<td class="col-lg-8 col-md-7 col-xs-10 font-size-large">
		<%= repo_list["name"].to_s %>
	</td>
	<td class="col-lg-2 col-md-2 col-xs-1 font-size-large statCount">
		<span id="repo_<%= repo_list["id"] %>_count"><%= repo_list["count"].to_s %></span>
	</td>
	<td class="text-right col-lg-2 col-md-3 col-xs-1">
		<div class="btn-group flex-btn-group-container">
			<%= link_to show_data_path(id: repo_list["id"]), 
						class: "btn btn-info btn-sm" do %>
				<span class="glyphicon glyphicon-eye-open"></span>
				<span class="hidden-xs hidden-sm"><%= t('data.details_label') %></span>
			<% end %>
			<%= link_to repo_delete_path(id: repo_list["id"]), 
						method: :delete,
						class: "btn btn-danger btn-sm",
						data: { confirm: t('data.delete_question') } do %>
				<span class="glyphicon glyphicon-remove-circle"></span>
				<span class="hidden-xs hidden-sm"><%= t('data.delete_label') %></span>
			<% end %>
		</div>
	</td>
	<script type="text/javascript">
		$(document).load( $.ajax({
			url: "<%= ENV["VAULT_URL"].to_s %>/api/repos/<%= repo_list["id"] %>/count",
			type: "GET",
			beforeSend: function (xhr) {
			    xhr.setRequestHeader('Authorization', 'Bearer <%= session["token"] %>');
			}
		}).done(function( data ) { $("#repo_<%= repo_list["id"] %>_count").text( data.count ) }));
	</script>
</tr>

app/views/users/data.html.erb
<% provide(:title, t('menu.data')) %>
<div class="row">
	<div class="col-xs-1">
		<%= link_to user_path, style: "text-decoration: none; color: black;" do %>
			<h1 style="text-align: left;"><i class="fa fa-arrow-left"></i></h1>
		<% end %>
	</div>
	<div class="col-xs-10">
		<h1><%= t('menu.data') %></h1>
	</div>
</div>
<p style="margin: 10px 0 20px;"><%= t('data.overview_text', record_count: @record_count, app_count: @apps_count) %>

<table id="data-table" class="table table-striped">
	<thead> 
		<tr>
			<th><span class="font-size-large"><%= t('data.repo_title') %></span></th>
			<th class="statCount"><span class="font-size-large"><%= t('data.record_title') %></span></th>
			<th class="center"><span class="font-size-large"><%= t('data.action_title') %></span></th>
		</tr>
	</thead>
	<tbody>
		<%= render partial: "repo_list", collection: @repos.sort_by { |item| item["name"].downcase } %>
	</tbody>
</table>

app/views/users/permissions.html.erb
<% provide(:title, t('menu.permission')) %>
<%= link_to user_path, style: "text-decoration: none; color: black;" do %><h1 style="text-align: left;"><i class="fa fa-arrow-left"></i> <%= t('menu.permission') %></h1><% end %>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  </div>
</div>

<a href="#" data-toggle="modal" data-target="#customManifest" class="btn btn-primary"><i class="fa fa-plus"></i> <%= t('data.addPlugin') %></a>

<table id="data-table" class="table table-striped">
	<thead> 
		<tr>
			<th><span class="font-size-large"><%= t('data.plugin_title') %></span></th>
			<th class="center"><span class="font-size-large"><%= t('data.action_title') %></span></th>
		</tr>
	</thead>
	<tbody>
		<%= render partial: "plugin_list", collection: @plugins.sort_by { |item| item[:name] } %>
	</tbody>
</table>

<!-- Details Modal -->
<div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="detailsHeader">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="detailsHeader"></h4>
			</div>
			<%= form_with url: plugin_update_path do |form| %>
				<div class="modal-body">
					<ul class="nav nav-tabs" data-tabs="tabs" id="detail_tabs" style="margin-top: 0;">
						<li class="active"><a data-toggle="tab" href="#general"><%= t('apps.generalTab') %></a></li>
						<li><a data-toggle="tab" href="#permissions"><%= t('apps.permissionsTab') %></a></li>
					</ul>

					<div class="tab-content">
						<div class="tab-pane active" id="general">
							<%= form.hidden_field :details_plugin_id, id: "details_plugin_id" %>
							<div class="form-group">
								<label class="control-label" for="details_view_name"><%= t('apps.name') %></label>
								<%= form.text_field :details_plugin_name, id: "details_plugin_name", class: "form-control" %>
							</div>
							<div class="form-group">
								<label class="control-label" for="details_app_key"><%= t('apps.app_key') %></label>
								<input class="form-control" id="details_app_key" readonly>
							</div>
							<div class="form-group">
								<label class="control-label" for="details_app_secret"><%= t('apps.app_secret') %></label>
								<input class="form-control" id="details_app_secret" readonly>
<!--								<div class="input-group">
									<input type="password" class="form-control" style="font: small-caption; font-size: 16px; line-height: 1.3em;" id="details_app_secret" readonly>
									<span class="input-group-btn"> 
										<%= link_to(show_app_details_password_path(app_id: params[:app_id]), class: "btn btn-default fakebutton", remote: true) do  %>
										<span class="glyphicon glyphicon-eye-open"></span>
										<% end %>
									</span>
								</div>-->
							</div>
<!--							<div class="form-group">
								<label class="control-label" for="details_view_url"><%= t('apps.app_url') %></label>
								<%= form.text_field :details_view_url, id: "details_view_url", class: "form-control" %>
							</div>-->
						</div>
						<div class="tab-pane" id="permissions">
							<table class="table table-hover" id="permTable" style="overflow-y: scroll;height: 320px;display: block;">
								<thead>
									<tr>
										<th style="width: 100%;"><%= t('apps.repo') %></th> 
										<th class="text-center"><%= t('apps.readPerm') %></th> 
										<th class="text-center"><%= t('apps.writePerm') %></th> 
										<th class="text-center"><%= t('apps.updatePerm') %></th> 
										<th class="text-center"><%= t('apps.deletePerm') %></th> 
									</tr> 
								</thead>
								<tbody id="listPermissions">
								</tbody> 
							</table>
							<button type="button" class="btn btn-info btn-sm" id="addPerm"><%= t('apps.addPermBtn') %></button>
							<script type="text/javascript">
								$('#addPerm').click(function() {
									var cnt = parseInt($('#permTable tr:last input:first').attr('id').split('_')[2])+1;
									var newTr = "<tr>";
									newTr = newTr.concat('<td><input type="text" id="perm_IDENTIFIER_', cnt, '" name="perm_IDENTIFIER_', cnt, '" style="margin-bottom: 0; width: 90%;">');
									newTr = newTr.concat('<span class="deletePerm" onclick="$(this).closest(\'tr\').hide();$(\'#perm_IDENTIFIER_', cnt, '_delete\').val(\'true\');"><i class="fa fa-trash" aria-hidden="true"></i></span>')
									newTr = newTr.concat('<input type="hidden" id="perm_IDENTIFIER_', cnt, '_delete" name="perm_IDENTIFIER_', cnt, '_delete" value="false">');
									newTr = newTr.concat('</td>');
									newTr = newTr.concat('<td class="text-center permission" id="perm_READ_', cnt, '">');
									newTr = newTr.concat('<input type="hidden" id="perm_READ_', cnt, '_value" name="perm_READ_', cnt, '_value" value="false">');
									newTr = newTr.concat('<i class="fa fa-square-o" aria-hidden="true"></i></td>');
									newTr = newTr.concat('<td class="text-center permission" id="perm_WRITE_', cnt, '">');
									newTr = newTr.concat('<input type="hidden" id="perm_WRITE_', cnt, '_value" name="perm_WRITE_', cnt, '_value" value="false">');
									newTr = newTr.concat('<i class="fa fa-square-o" aria-hidden="true"></i></td>');
									newTr = newTr.concat('<td class="text-center permission" id="perm_UPDATE_', cnt, '">');
									newTr = newTr.concat('<input type="hidden" id="perm_UPDATE_', cnt, '_value" name="perm_UPDATE_', cnt, '_value" value="false">');
									newTr = newTr.concat('<i class="fa fa-square-o" aria-hidden="true"></i></td>');
									newTr = newTr.concat('<td class="text-center permission" id="perm_DELETE_', cnt, '">');
									newTr = newTr.concat('<input type="hidden" id="perm_DELETE_', cnt, '_value" name="perm_DELETE_', cnt, '_value" value="false">');
									newTr = newTr.concat('<i class="fa fa-square-o" aria-hidden="true"></i></td>');
									newTr = newTr.concat('</tr>');
									$('#permTable tr:last').after(newTr);
								})
							</script>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal"><%= t('dialog.closeBtn') %></button>
					<%= form.button t('apps.saveBtn'), 
							class: "btn btn-primary", style: "width: 200px;",
							data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> " + t('apps.saveBtn') } %>
				</div>
			<% end %>
		</div>
	</div>
</div>

<!-- Modal to manually add Manifest -->
<div class="modal fade" id="customManifest" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t('data.addPlugin') %></h4>
      </div>
      <%= form_with url: add_manifest_path do |form| %>
	      <div class="modal-body">
	        <div class="form-group">
			  <label for="manifest">Manifest:</label>
			  <%= form.text_area :manifest, rows: 5 %>
			</div>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('dialog.closeBtn') %></button>
			<%= form.button t('dialog.submitBtn'), 
					class: "btn btn-primary", style: "width: 200px;",
					data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> " + t('dialog.submitBtn') } %>
	      </div>
	  <% end %>
    </div>
  </div>
</div>

app/views/users/pia_delete.js.erb
<% if @invalidPwd %>
	$('#invalidPwdPiaDeleteMsg').show();
	$('#invalidPwdPiaDeleteMsg').text("<%= t('data.invalidPwd') %>");
<% end %>