config/routes.rb
Rails.application.routes.draw do
	mount Rswag::Ui::Engine => '/api-docs'
	mount Rswag::Api::Engine => '/api-docs'

	match '/oauth/authorize', to: 'oauth_applications#new',    via: 'get'
	match '/oauth/authorize', to: 'oauth_applications#create', via: 'post'

	use_doorkeeper
	devise_for :users

	# API Routes ==============
	namespace :api, defaults: { format: :json } do
		scope module: :v1,
			constraints: ApiConstraints.new(version: 1, default: true) do

				# Statistics
				match 'stats',                  to: 'stats#index',            via: 'get'

				# DEC112
				match '/dec112/register',       to: 'decs#register',          via: 'post'
				match '/dec112/query/:did',     to: 'decs#query',             via: 'get', constraints: {did: /[^\/]+/}
				match '/dec112/revoke',         to: 'decs#revoke',            via: 'delete'

				# SC Consent
				match '/consent',               to: 'consents#create',        via: 'post'
				match '/consent',               to: 'consents#index',         via: 'get'
				match '/consent/:id',           to: 'consents#show',          via: 'get'
				match '/consent/:id',           to: 'consents#update',        via: 'put'
				match '/consent/:id',           to: 'consents#delete',        via: 'delete'

				# QR Code handling
				match 'read_qr/:did',			to: 'qrs#read',               via: 'get', constraints: {did: /[^\/]+/}
				match 'connect',                to: 'qrs#qr_connect',         via: 'post'

				# App support
				match 'support/:nonce',         to: 'users#support',          via: 'get'
				match 'install/:key',           to: 'installs#show',          via: 'get'

				# User handling
				post 'users/create',            to: 'users#create'
				post 'users/confirm',           to: 'users#confirm'
				get  'users/show',              to: 'users#show'
				post 'users/do_remember',       to: 'users#do_remember'
				post 'users/remember',          to: 'users#remember'
				post 'users/forget',            to: 'users#forget'
				post 'users/update', 			to: 'users#update'
				post 'users/update_pwd',        to: 'users#update_pwd'
				post 'users/update_recv_pwd',   to: 'users#update_recv_pwd'
				get  'users/name_by_token/:id', to: 'users#name_by_token'
				get  'users/record_count',      to: 'users#record_count'
				get  'users/access_count',      to: 'users#access_count'
				match 'users/current',          to: 'users#current',          via: 'get'
				match 'users/archive',          to: 'users#archive',          via: 'get'
				match 'users/delete',           to: 'users#delete',           via: 'get'
				match 'users/app_support',      to: 'users#app_support',      via: 'post'
				match 'users/statistics',       to: 'users#statistics',       via: 'get'
				match 'users/hints',            to: 'users#hints',            via: 'get'
				match 'users/inactive_sources', to: 'users#inactive_sources', via: 'get'
				match 'users/reset_password',   to: 'users#reset_password',   via: 'post'
				match 'users/perform_password_reset', to: 'users#perform_password_reset', via: 'post'

				# App/Plugin handling
				get   'apps/index',             to: 'apps#index'
				post  'apps/destroy',           to: 'apps#destroy'
				match 'apps/:id',               to: 'apps#update', via: 'put'
				match 'apps/:id',               to: 'apps#show',   via: 'get'

				# true plugins (Doorkeeper::Application)
				match 'plugins/index',           to: 'plugins#index',           via: 'get'
				match 'plugins/create',          to: 'plugins#create',          via: 'post'
				match 'plugins/current',         to: 'plugins#current',         via: 'get'
				match 'plugins/:id',             to: 'plugins#show',            via: 'get'
				match 'plugins/:id',             to: 'plugins#update',          via: 'put'
				match 'plugins/:id',             to: 'plugins#delete',          via: 'delete'
				match 'plugins/identifier/:id',  to: 'plugins#show_identifier', via: 'get', constraints: {id: /[^\/]+/}
				# match 'plugins/:id/configure',   to: 'plugins#configure', via: 'post'
				match 'plugins/:id/manifest',    to: 'plugins#manifest_update', via: 'put'
				match  '/plugin/:id/assist',     to: 'plugins#assist',          via: 'get', constraints: {id: /[^\/]+/}
				match  '/plugin/:id/assist',     to: 'plugins#assist_update',   via: 'put', constraints: {id: /[^\/]+/}

				# Source handling
				match 'sources/index',           to: 'sources#index',     via: 'get'
				match 'sources/inactive',        to: 'sources#inactive',  via: 'get'
				match 'sources/:id',             to: 'sources#show',      via: 'get'
				match 'sources/:id',			 to: 'sources#update',    via: 'put'
				match 'sources/:id',             to: 'sources#delete',    via: 'delete'
				match 'sources/:id/configure',   to: 'sources#configure', via: 'post'
				match 'sources/:id/pile',        to: 'sources#new_pile',  via: 'post'
				match 'sources/:id/last_pile',   to: 'sources#last_pile', via: 'get'
				match 'piles/:id',               to: 'sources#show_pile', via: 'get'

				# View handling
				match 'views/:id',    to: 'views#update', via: 'put'
				match 'views/:id',    to: 'views#show',   via: 'get'
				# legacy for animal mobile oyd app
				match 'modules/index', to: 'views#mobile_index', via: 'get'
				
				# Permission handling
				match 'apps/:plugin_id/perms',         to: 'perms#index',      via: 'get'
				match 'apps/:plugin_id/perms',         to: 'perms#create',     via: 'post'
				match 'apps/:plugin_id/perms/:id',     to: 'perms#update',     via: 'put'
				match 'apps/:plugin_id/perms/:id',     to: 'perms#delete',     via: 'delete'
				match 'apps/:plugin_id/perms_destroy', to: 'perms#delete_all', via: 'post'

				# Permission handling
				match 'plugins/:plugin_id/perms',         to: 'perms#index',      via: 'get'
				match 'plugins/:plugin_id/perms',         to: 'perms#create',     via: 'post'
				match 'plugins/:plugin_id/perms/:id',     to: 'perms#update',     via: 'put'
				match 'plugins/:plugin_id/perms/:id',     to: 'perms#delete',     via: 'delete'
				match 'plugins/:plugin_id/perms_destroy', to: 'perms#delete_all', via: 'post'

				# Repo handling
				match 'repos/index',           to: 'repos#index',   via: 'get'
				match 'repos/:id',             to: 'repos#show',    via: 'get'
				match 'repos(/:identifier)/identifier', to: 'repos#show_identifier', via: 'get', constraints: {identifier: /[^\/]+/}
				match 'repos/:id',             to: 'repos#delete',  via: 'delete'
				match 'repos/:id/items',       to: 'repos#items',   via: 'get'
				match 'repos/:id/count',       to: 'repos#count',   via: 'get'
				match 'repos/:id/pub_key',     to: 'repos#pub_key', via: 'get', constraints: {id: /[^\/]+/}
				# Repos for apps
				match 'apps/:plugin_id/repos', to: 'repos#apps',    via: 'get'

				# Item handling
				match 'repos/id/:id/items',                   to: 'items#index_id',  via: 'get'
				match 'repos/id/:repo_id/items/:id',          to: 'items#delete_id', via: 'delete'
				match 'repos(/:repo_identifier)/items',       to: 'items#create',    via: 'post',   constraints: {repo_identifier: /[^\/]+/}
				match 'repos(/:repo_identifier)/items',       to: 'items#index',     via: 'get',    constraints: {repo_identifier: /[^\/]+/}
				match 'repos(/:repo_identifier)/items/:id',   to: 'items#update',    via: 'put',    constraints: {repo_identifier: /[^\/]+/}
				match 'repos(/:repo_identifier)/items/:id',   to: 'items#delete',    via: 'delete', constraints: {repo_identifier: /[^\/]+/}
				match 'items/:id/details',                    to: 'items#details',   via: 'get',    as: "item_id"
				match 'dri/:dri/details',                     to: 'items#dri',       via: 'get'
				match 'items/count', 						  to: 'items#count',     via: 'get'

				# Item handling /api/data
				match '/data',                                to: 'data#index',       via: 'get'
				match '/data/:id',                            to: 'data#index',       via: 'get'
				match '/data',                                to: 'data#write',       via: 'post'
				match '/data/:id',                            to: 'data#write',       via: 'put'
				match '/data/:id', 							  to: 'data#delete',      via: 'delete'
				match '/meta/schemas',                        to: 'semantics#schema', via: 'get'
				match '/meta/tables',                         to: 'semantics#table',  via: 'get'
				match '/meta/info',                           to: 'semantics#info',   via: 'get'
				match '/meta/usage',                          to: 'users#usage',      via: 'get'
				match '/active',                              to: 'semantics#active', via: 'get'				

				#watermarking
				match 'watermark/recipients', to: 'watermarks#recipients', via: 'get'
				match 'watermark/:id',        to: 'watermarks#show',       via: 'get'
				match 'watermark/:id',        to: 'watermarks#apply',      via: 'post'

				# Scheduler
				match 'tasks/index',  to: 'tasks#index',  via: 'get'
				match 'tasks/active', to: 'tasks#active', via: 'get'
				match 'tasks/create', to: 'tasks#create', via: 'post'
				match 'tasks/:id',    to: 'tasks#update', via: 'put',   constraints: {id: /[^\/]+/}
				match 'tasks/:id',    to: 'tasks#delete', via: 'delete'

				# Answers
				match 'answers/index', to: 'answers#index', via: 'get'
				match 'answers/:id',   to: 'answers#show',  via: 'get'

				# Reports
				match 'reports/index', to: 'reports#index',  via: 'get'
				match 'reports/:id',   to: 'reports#show',   via: 'get'
				match 'reports/:id',   to: 'reports#update', via: 'put'

				# Logs
				match 'logs/index',  to: 'logs#index',  via: 'get'
				match 'logs/create', to: 'logs#create', via: 'post'

				# Blockchain
				match 'items/merkle',   to: 'items#merkle',             via: 'get'
				match 'items/:id',      to: 'items#item_merkle_update', via: 'put'
				match 'merkles/create', to: 'items#merkle_create',      via: 'post'
				match 'merkles/:id',    to: 'items#merkle_update',      via: 'put'

				# News
				match 'news', to: 'news#current', via: 'get'

				# Sharing & Watermarking

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
	  <nav>
	    <ul style="padding-right: 120px;">
	      <li><%= link_to "OwnYourData.eu", 'https://www.ownyourdata.eu' %> © 2022</li>
	      <li><%= link_to t('footer.security'), 'https://www.ownyourdata.eu/' + I18n.locale.to_s + '/#data_security' %></li>
	      <li><%= link_to t('footer.impressum'), 
	      			I18n.locale.to_s == "de" ? 'https://www.ownyourdata.eu/de/impressum/' : 'https://www.ownyourdata.eu/en/imprint/' %></li>
	      <li><%= link_to "MyData Operator 2022", 'https://www.ownyourdata.eu/' + I18n.locale.to_s + '/ownyourdata-is-mydata-operator-2020/' %></li>
	    </ul>
	  </nav>
	  <nav>
	    <ul style="float:right;">

        <div class="btn-group dropup" style="margin-right: 15px;">
          <button type="button" class="fakelink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-flag"></span>
            <span class="font-size-large" style="font-size:14px;"><%= t('footer.language') %></span> 
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu dropdown-menu-right">
            <li><%= link_to "Deutsch", { locale: 'de', token: params[:token] } %></li>
            <li><%= link_to "English", { locale: 'en', token: params[:token] } %></li>
          </ul>
        </div>
	    </ul>
	  </nav>

	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <nav>
    	<%= link_to root_path, class: "navbar-brand" do %>
    		<div class="pia-logo"></div>
    		<div class="logo-txt">
    			<span class="font-size-large"><%= t('general.title') %></span>
    		</div>
    	<% end %>
    </nav>
    <nav>
      <ul style="float:right;">
        <% if logged_in? %>
        <!--
          <li><%= link_to t('menu.myApps'), user_path, 
            class: 'menulink' + (' active_menu' if current_page?(user_path)).to_s %></li>
          <li><%= link_to t('menu.myData'), data_path, 
            class: 'menulink' + (' active_menu' if current_page?(data_path)).to_s %></li>
          <li><%= link_to account_path, 
            class: 'menulink' + (' active_menu' if current_page?(account_path)).to_s do %>
            <span class="glyphicon glyphicon-user"></span>
            <%= t('menu.account') %>
          <% end %></li> -->
          <div class="btn-group dropdown" style="margin: 35px 15px -7px;">
            <a href="#" class="dropdown-toggle fakelink" style="font-size:15px;" data-toggle="dropdown">
              <span class="glyphicon glyphicon-user"></span></a>
            <a href="#" class="dropdown-toggle fakelink" style="font-size:15px; margin-left: -10px;" data-toggle="dropdown">
              <span class = 'hidden-xs'><%= current_user["full_name"] %></span> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li><%= link_to t('menu.source'), sources_path %></li>
              <li><%= link_to t('menu.data'), data_path %></li>
              <li><%= link_to t('menu.permission'), plugins_path %></li>
<!--              <li><%= link_to t('menu.question'), '#' %></li>
              <li><%= link_to t('menu.application'), '#' %></li>
              <li><%= link_to t('menu.source'), '#' %></li>
              <li><%= link_to t('menu.task'), '#' %></li> -->
              <li class="divider"></li>
              <li><%= link_to t('menu.access_log'), log_path %></li>
              <li><%= link_to t('menu.setting'), account_path %></li>
              <li><%= link_to t('menu.logoff'), logout_path, method: :delete %></li>
            </ul>
          </div>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield.dup.force_encoding(Encoding::UTF_8) %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application_map.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js'></script>
    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/Leaflet.fullscreen.min.js'></script>
    <script src="https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js"></script>
    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/leaflet.fullscreen.css' rel='stylesheet' />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/MarkerCluster.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/MarkerCluster.Default.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container" style="margin-top: 15px;">
      <%= yield.dup.force_encoding(Encoding::UTF_8) %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application_reload.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="refresh" content="10" />
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container" style="margin-top: 15px;">
      <%= yield.dup.force_encoding(Encoding::UTF_8) %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>